ADD : 기본 DAO 셋팅 및 utils/keyCheck.js 구현
wecode-bootcamp-korea/11-PrettyCloud-backend pull request #3
Opened 2020-09-05 09:44 UTC by eymin1259

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
ADD : 기본 DAO 셋팅 및 utils/keyCheck.js 구현		 

## 수정 사항들 자세한 내용
- DAO 셋팅 (호현님)
- req.body에서 필요한 키가 모두 전달 되어있는지 확인하는 함수 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-07 03:50 UTC, joonseokhu requested changes
Sequelize ORM이 알아서 DAO를 반환합니다. 따라서 DAO 파일 만들 필요 없습니다.
각 모델별에 따라 원하는 특정 메서드가 필요할 경우 sequelize 의 class methods 사용법을 검색해서 적용하세요

2020-09-07 03:50 UTC, joonseokhu commented on utils/keyCheck.js
> +module.exports = keyCheck;
이게 뭔지 알수있을까요?

2020-09-07 20:49 UTC, eymin1259 commented on utils/keyCheck.js
> +module.exports = keyCheck;
request에 원하는 키값이 모두 들어왔는지 검사하는 함수를 utils 디렉토리 안에 따로 작성하였습니다
keyCheck( ["i", "need", "this" , "key] , Object.keys(req.body) ) 이런식으로 사용하고 있습니다!

2020-09-07 23:54 UTC, eymin1259 commented on utils/keyCheck.js
> +module.exports = keyCheck;
그런데 노드에서는 굳이 키값이 모두 제대로 들어있는지 검사를 하지 않아도 에러핸들러 부분에서 예외를 처리할 수 있으니 굳이 필요 없는 부분인것 같습니다

2020-09-08 04:37 UTC, closed without merging

2020-09-08 04:39 UTC, eymin1259 commented
DAO와 keyCheck가 필요없는 부분이라서 위의 브랜치를 feature/SpaceList에 병합하고 rebase하여 하나의 커밋으로 PR 수정했습니다