ADD : 공간리스트 정보를 전달하는 api 구현
wecode-bootcamp-korea/11-PrettyCloud-backend pull request #4
Opened 2020-09-07 20:47 UTC by eymin1259

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
    ADD : 공간리스트 정보를 전달하는 api 구현

## 수정 사항들 자세한 내용
- spaceMain : 메인페이지에서 필요한 공간정보리스를 db에서 조회 및 전달, + offset,limit을 통한 페이지네이션 기능 구현
- spaceSearch : 검색결과페이지에서 필요한 공간정보리스트를 db에서 조회 및 전달 + offset, limit을  이용하여 페이지네이션 기능 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-08 17:30 UTC, joonseokhu requested changes
1. 홑따옴표 쓰세요
2. let 아끼세요. 최대한 let 쓰지 마세요
3. 조건문 아끼세요. 조건문으로 함수 전체가 감싸져있는게 많던데, 그러면 그냥 함수 두개여야 하는겁니다. https://velog.io/@kskim/%ED%95%A8%EC%88%98%EC%9D%98-%EB%8B%A8%EC%9D%BC-%EC%B1%85%EC%9E%84-%EC%A1%B0%EA%B1%B4%EC%9D%84-%EC%B6%A9%EC%A1%B1%EC%8B%9C%EC%BC%9C%EB%9D%BC-else%EB%AC%B8%EC%9D%84-%EB%B0%B0%EC%A0%9C%ED%95%B4%EB%9D%BC

2020-09-08 17:30 UTC, joonseokhu commented on controllers/spaceMain.js
> +    let reqLimit = req.query.limit;
1. 굳이 변수명이 offset 이 아니라 reqOffset인지 모르겠네요
2. let 키워드는 거의 쓸 필요가 없습니다. const로 써주세요.
3. 비구조화할당으로 처리하세요

2020-09-08 17:30 UTC, joonseokhu commented on controllers/spaceMain.js
> +    if (reqOffset == 0 && reqLimit == 6) {
이렇게 거대한 if 문 생기는건 보통 내가 뭔가를 잘못하고 있다는 뜻입니다..
메인페이지에서 쓰는 모든 데이터를 다 뭉쳐서 주시는것 같은데, 백엔드와 프론트엔드로 개발 포지션을 나뉘어져있는 이유중 하나는 백엔드가 DDD를 하기 위함입니다.
도메인별로 api 다 분리해주시고, 프론트엔드에서 메인페이지 만들때 필요한 데이터 종류에 따라 따로따로 api 호출 여러번 하도록 해주세요

2020-09-08 17:30 UTC, joonseokhu commented on controllers/spaceMain.js
> +      });
```js
resData.mainSlider = await models.model.Collections.findAll({
  attributes: ["id", "title", "img_url", "description"],
})
```
이렇게 쓰는거랑 차이가 뭘까요..?

2020-09-08 17:30 UTC, joonseokhu commented on controllers/spaceMain.js
> +      );
특별한 상황 아니면 반복문 안에서 sql 문 처리 안하도록 해주세요. Spaces 와 space_id 로 관계설정된것 같은데, sequelize의 include 가지고 이미지랑 카테고리 둘다 space 에 join 되도록 만들수 있습니다.

2020-09-08 17:30 UTC, joonseokhu commented on controllers/spaceMain.js
> +          let location = elem.dataValues.address.split("구")[0].split(" ")[1];
이게 주소에서 "XX시" 부분을 찾는건가요?
정규표현식이 훨씬 정확하고 깔끔합니다.
`address.match(/^[가-힣]+시(?=\s)/)`

<img width="368" alt="스크린샷 2020-09-09 오전 2 28 52" src="https://user-images.githubusercontent.com/19492260/92508825-3b036e80-f244-11ea-836a-314734671ab1.png">

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceMain.js
> +      );
여기도 sql 에 의한 비동기 반복문 최대한 없이, 다 join 처리 해주세요

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceMain.js
> +    }
이쪽은 앞에서 리뷰한 부분과 겹치니 설명 생략하겠습니다.
앞서 말했듯, 해당 코드를 고쳐서 끝나면 안됩니다.

resData.mainSlider = [];
 resData.categories = [];
 resData.recommendation = [];
 resData.userReviews = [];

얘네들이 하나의 라우트에서 처리되면 안되고 다 별개의 라우트, 별개의 컨트롤러에서 처리되어야 각각 처리 되어야 합니다.

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +const { sequelize } = require("../models/index");
여기도 import  고쳐주세요

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +const get = async function (req, res, next) {
여기도 화살표함수 써주세요

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +    const resData = {};
여기도 객체 만들어두고 append 하는 형태로 처리하지 마시고
const 로 각각 변수처리한다음에 response 에서 리터럴로 쓰시면 됩니다.

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +    const qString = req.query.search;
여기도 비구조화 할당 해주세요

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +    if (reqOffset == 0 && reqLimit == 6) {
여기도... 백엔드는 이게 프론트엔드에서 초기검색결과일지말지 별로 안궁금해야 합니다. 이런걸로 조건문처리하지 마세요

2020-09-08 17:57 UTC, joonseokhu commented on models/Reservations.js
> +      deletedAt: "deleted_at",
홑따옴표 쓰세요

2020-09-08 17:57 UTC, joonseokhu commented on models/Users.js
> +        defaultValue: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU'
기본 이미지 처리는 프론트엔드에서 해야합니다.

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +      );
1. Images 도 join 같이 할수 있을것같은데 굳이 반복문으로 왜 뺐는지 모르겠습니다
2. raw query 없이 sequelize 에서 처리 가능합니다.
3. 각 space 별로 카테고리 목록을 뽑아야 하는건가요? 시퀄라이즈에서 가능하니 시퀄라이즈 써서 처리해주세요

한 쿼리로 처리하시고, 또는 시퀄라이즈 함수 하나로 처리하시고
주소부분 문자열 처리하는 부분만 반복문으로 처리하면 됩니다.

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +      );
프리미엄,플러스,노말 --> 얘네 세개, 조회할때 조건 한가지만 다르고 나머지 로직은 다 똑같은거같은데, 함수로 만들어서 코드 재사용 하세요

2020-09-08 17:57 UTC, joonseokhu commented on controllers/spaceSearch.js
> +    }
음... 목록 세개를 함께 보내는거군요
프론트에서 세번 각각 요청하게 해주세요

2020-09-08 18:11 UTC, joonseokhu commented on controllers/spaceMain.js
> +          let location = elem.dataValues.address.split("구")[0].split(" ")[1];
https://regexr.com/

2020-09-08 18:19 UTC, joonseokhu commented on controllers/spaceDetail.js
> +    );
1. 왠만하면 시퀄라이즈로 처리해주세요. 

```js
Spaces.find({
  where: {
   space_id: spaceId,
  },
  include: [
    Categories,
    Images,
  ],
})
```

2. 연결테이블인 SpaceCategory 기준으로 조인하는게 더 깔끔합니다.

2020-09-09 05:24 UTC, eymin1259 commented on controllers/spaceDetail.js
> +const { sequelize } = require("../models/index");
수정했습니다 !

2020-09-09 05:43 UTC, eymin1259 commented on controllers/spaceDetail.js
> +const get = async function (req, res, next) {
화살표 함수로 수정했습니다!

2020-09-09 05:45 UTC, eymin1259 commented on controllers/spaceDetail.js
> +    const spaceInfo = await models.model.Spaces.findByPk(spaceId);
const { sequelize, Spaces, Images, Reviews } = require('../models'); 
이런식으로 import하여 바로 await Spaces.findByPk(spaceId); 이렇게 사용하였습니다!

2020-09-09 05:54 UTC, eymin1259 commented on controllers/spaceDetail.js
> +    res.status(201).json(resData);
자바스크립트 방식으로 수정했습니다!

2020-09-09 06:27 UTC, eymin1259 commented on controllers/spaceDetail.js
> +    const spaceId = parseInt(req.params.spaceId);
Number로 수정하였습니다!

2020-09-09 08:18 UTC, eymin1259 commented on controllers/spaceDetail.js
> +    );
sql 쿼리문을  sequelize의 include를 이용하여 변경하였습니다!

2020-09-09 08:19 UTC, eymin1259 commented on controllers/spaceMain.js
> +const { sequelize } = require("../models/index");
수정하였습니다!

2020-09-09 08:19 UTC, eymin1259 commented on controllers/spaceMain.js
> +const get = async function (req, res, next) {
수정하였습니다!

2020-09-09 08:20 UTC, eymin1259 commented on controllers/spaceMain.js
> +    let reqLimit = req.query.limit;
왠만한 let 키워드를 const로 대체하였습니다.
변수명 reqOffset, reqLimit으로 굳이 설정한 이유가 없어서 offset, limit으로 변경하였습니다!

2020-09-09 08:21 UTC, eymin1259 commented on controllers/spaceMain.js
> +    if (reqOffset == 0 && reqLimit == 6) {
도메인별로 api 다 분리하여, 필요한 데이터 종류에 따라 별도로 api 호출 하도록 수정하였습니다!

2020-09-09 08:22 UTC, eymin1259 commented on controllers/spaceMain.js
> +      });
차이가 없습니다.. ^^:; 수정하였습니다!

2020-09-09 08:24 UTC, eymin1259 commented on controllers/spaceMain.js
> +      );
이 부분을 수정해야 될 것 같다고 생각했는데 어떻게 바꿔야 될지 몰라서 그냥 반복문을 썼었습니다 ..
include를 사용하여 반복문을 제거하였습니다!

2020-09-09 08:25 UTC, eymin1259 commented on controllers/spaceMain.js
> +      );
include를 사용하여 수정하였습니다!

2020-09-09 08:25 UTC, eymin1259 commented on controllers/spaceMain.js
> +    }
별개의 컨트롤러에서 처리되도록 수정하였습니다!

2020-09-10 01:47 UTC, eymin1259 commented on controllers/spaceMain.js
> +          let location = elem.dataValues.address.split("구")[0].split(" ")[1];
정규표현식을 적용하였습니다!

2020-09-10 01:47 UTC, eymin1259 commented on controllers/spaceSearch.js
> +const { sequelize } = require("../models/index");
수정하였습니다!

2020-09-10 01:47 UTC, eymin1259 commented on controllers/spaceSearch.js
> +    const resData = {};
수정하였습니다!

2020-09-10 01:48 UTC, eymin1259 commented on models/Users.js
> +        defaultValue: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU'
수정하였습니다

2020-09-10 01:49 UTC, eymin1259 commented on controllers/spaceSearch.js
> +    if (reqOffset == 0 && reqLimit == 6) {
수정하였습니다

2020-09-10 01:50 UTC, eymin1259 commented on controllers/spaceSearch.js
> +      );
raw query를 사용하지 않고 sequelize의 include 를 사용하여 처리하였습니다!
이후 db에서 얻은 데이터를 가공하는 부분만 반복문으로 처리하였습니다!

2020-09-10 01:51 UTC, eymin1259 commented on controllers/spaceSearch.js
> +      );
utlis에 검색기능을 가진 함수를 구현하고 필요한 controller에서 import하는 방식으로 수정하였습니다!

2020-09-10 01:51 UTC, eymin1259 commented on controllers/spaceDetail.js
> +    );
sequlize로 처리하였습니다!

2020-09-10 01:52 UTC, eymin1259 commented on controllers/spaceSearch.js
> +    }
Domain Driven Development 방식에 맞게 수정하였습니다!

2020-09-10 06:32 UTC, joonseokhu approved these changes

2020-09-10 06:32 UTC, joonseokhu commented on utils/searchSpaces.js
> +        },
```js
'%' + qString + '%'
// 이렇게 변경 가능합니다.
`%${qString}%`
```

2020-09-10 06:32 UTC, merged

2020-09-10 07:43 UTC, eymin1259 commented on utils/searchSpaces.js
> +        },
템플릿 문자열을 활용하여 수정하였습니다!