[이호현] ADD: 회원가입, 로그인 API
wecode-bootcamp-korea/11-PrettyCloud-backend pull request #5
Opened 2020-09-08 01:36 UTC by LeeHoHyun-hemtory

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-회원가입, 로그인 API 제작중입니다	 

## 수정 사항들 자세한 내용
- signupController: 회원가입, password bcrypt 변환 후 저장
- signinController: 로그인, id, email로 token 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 어제 프론트랑 연동하려고 해봤는데 500 internal server error가 뜨더라구요
그래서 집에서 혼자 리액트로 fetch도 해봤는데 마찬가지였습니다
제가 뭔가 빼먹은게 있는지 아니면 다른 이유가 있는지 궁금합니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-08 18:08 UTC, joonseokhu requested changes

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signinController.js
> +    }
해당 아이디가 존재하지 않는것과, 패스워드가 틀린건 보안상 구분되지 말아야 합니다. 둘다 그냥 로그인 실패라고만 알려주세요

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signupController.js
> +    }
요청 밸리데이션 할때 현업에선 https://express-validator.github.io/docs/ 같은걸 씁니다.

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signupController.js
> +    await sequelize.query(`INSERT INTO users VALUES(DEFAULT, "${email}", "${name}", "", "${hashPw}", "${profile_url ? profile_url : 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToplStyx8p
프로필이미지 기본값 넣어주지 마세요. 이미지 nullable 한 필드로 만드시고, 프론트엔드가 해당필드 null 이면 알아서 처리하게 하세요.

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signupController.js
> +    await sequelize.query(`INSERT INTO users VALUES(DEFAULT, "${email}", "${name}", "", "${hashPw}", "${profile_url ? profile_url : 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToplStyx8p
insert 문 칠때 시퀄라이즈의 create 메서드 쓰세요.

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signinController.js
> +    await sequelize.query(`SELECT * FROM users WHERE email="${email}"`, {
시퀄라이즈 findOne 으로 처리하세요

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signinController.js
> +      email
user pk 만 있으면 됩니다. 토큰에 개인정보 들어있으면 개인정보관련법 관련해서 위험할 여지가 생깁니다.

2020-09-08 18:08 UTC, joonseokhu commented on controllers/signupController.js
> +    await sequelize.query(`SELECT * FROM users WHERE email="${email}"`, {
시퀄라이즈 이용해서 처리해보세요

2020-09-08 18:55 UTC, LeeHoHyun-hemtory commented on controllers/signinController.js
> +    }
수정했습니다

2020-09-09 02:43 UTC, joonseokhu commented on controllers/signupController.js
> +    }
현재 프로젝트에 실제로 구현하긴 어려우니 참고만 해주세요~

2020-09-09 05:01 UTC, LeeHoHyun-hemtory commented on controllers/signupController.js
> +    }
넵
링크 주신곳 한번 보겠습니다

2020-09-09 05:03 UTC, LeeHoHyun-hemtory commented on controllers/signinController.js
> +      email
수정하겠습니다

2020-09-09 10:01 UTC, LeeHoHyun-hemtory commented on controllers/signupController.js
> +    await sequelize.query(`INSERT INTO users VALUES(DEFAULT, "${email}", "${name}", "", "${hashPw}", "${profile_url ? profile_url : 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToplStyx8p
PR에 내용을 적긴했는데요
`sequelize` 사용법을 따로 공부해도 괜찮을까요
`method` 적용하려고 하니까 계속 제대로 안되서요.

2020-09-09 10:37 UTC, joonseokhu commented
먼저, `models/index.js` 에서 export 시
```js
module.exports = { sequelize, ...model }
```
로 export 하세요.

그런다음 현재 파일에서 import 시 이렇게 할수 있습니다.

```js
const { sequelize, Spaces, Categories, Images } = require('../models')

// 조회하면서 조인
const findOneSpaceAndJoinThings = async (spaceId) => {
  const result = await Spaces.findOne({
    where: {
      id: spaceId
    },
    include: [
      Categories,
      Images,
    ]
  })
  // result 가지고 뭐 하기
}

// 생성
const createSpace = async ({ title }) => {
  const result = await Spaces.create({
    title: title,
  })
  // result 가지고 뭐 하기
}
```

참고
- https://sequelize.org/master/manual/model-instances.html#creating-an-instance
- https://helloinyong.tistory.com/108
- https://jeonghwan-kim.github.io/sequalize-%EC%BF%BC%EB%A6%AC/

2020-09-09 12:12 UTC, joonseokhu commented on controllers/signinController.js
> +      expiresIn: '10s',
테스트하셨던거였죠..?

2020-09-09 14:53 UTC, LeeHoHyun-hemtory commented on controllers/signinController.js
> +      expiresIn: '10s',
넵
토큰 만료되면 어떻게 메세지 보내는지 확인해봤습니다

2020-09-10 06:36 UTC, joonseokhu commented
- [ ] 방금 merge 된 용민님 PR에서 시퀄라이즈 적용한 사례 있을겁니다. 참고해주세요~
- [ ] 용민님 pr merge 되면서 컨플릭트가 생겼습니다. 해소해서 푸시해주시면 됩니다.

2020-09-11 12:45 UTC, merged